=== wrekah/community-builds/build-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/your-schema#",
  "type": "object",
  "properties": {
    "champion": {
      "type": "string"
    },
    "sanitizedName": {
      "type": "string",
      "enum": [
        "aatrox",
        "ahri",
        "akali",
        "akshan",
        "alistar",
        "amumu",
        "anivia",
        "annie",
        "aphelios",
        "ashe",
        "aurelion-sol",
        "azir",
        "bard",
        "belveth",
        "blitzcrank",
        "brand",
        "braum",
        "briar",
        "caitlyn",
        "camille",
        "cassiopeia",
        "chogath",
        "corki",
        "darius",
        "diana",
        "draven",
        "dr-mundo",
        "ekko",
        "elise",
        "evelynn",
        "ezreal",
        "fiddlesticks",
        "fiora",
        "fizz",
        "galio",
        "gangplank",
        "garen",
        "gnar",
        "gragas",
        "graves",
        "gwen",
        "hecarim",
        "heimerdinger",
        "hwei",
        "illaoi",
        "irelia",
        "ivern",
        "janna",
        "jarvan-iv",
        "jax",
        "jayce",
        "jhin",
        "jinx",
        "kaisa",
        "kalista",
        "karma",
        "karthus",
        "kassadin",
        "katarina",
        "kayle",
        "kayn",
        "kennen",
        "khazix",
        "kindred",
        "kled",
        "kogmaw",
        "ksante",
        "leblanc",
        "lee-sin",
        "leona",
        "lillia",
        "lissandra",
        "lucian",
        "lulu",
        "lux",
        "malphite",
        "malzahar",
        "maokai",
        "master-yi",
        "milio",
        "miss-fortune",
        "mordekaiser",
        "morgana",
        "naafiri",
        "nami",
        "nasus",
        "nautilus",
        "neeko",
        "nidalee",
        "nilah",
        "nocturne",
        "nunu-and-willump",
        "olaf",
        "orianna",
        "ornn",
        "pantheon",
        "poppy",
        "pyke",
        "qiyana",
        "quinn",
        "rakan",
        "rammus",
        "reksai",
        "rell",
        "renata-glasc",
        "renekton",
        "rengar",
        "riven",
        "rumble",
        "ryze",
        "samira",
        "sejuani",
        "senna",
        "seraphine",
        "sett",
        "shaco",
        "shen",
        "shyvana",
        "singed",
        "sion",
        "sivir",
        "skarner",
        "sona",
        "soraka",
        "swain",
        "sylas",
        "syndra",
        "tahm-kench",
        "taliyah",
        "talon",
        "taric",
        "teemo",
        "thresh",
        "tristana",
        "trundle",
        "tryndamere",
        "twisted-fate",
        "twitch",
        "udyr",
        "urgot",
        "varus",
        "vayne",
        "veigar",
        "velkoz",
        "vex",
        "viego",
        "vi",
        "viktor",
        "vladimir",
        "volibear",
        "warwick",
        "wukong",
        "xayah",
        "xerath",
        "xin-zhao",
        "yasuo",
        "yone",
        "yorick",
        "yuumi",
        "zac",
        "zed",
        "zeri",
        "ziggs",
        "zilean",
        "zoe",
        "zyra"
      ]
    },
    "name": {
      "type": "string"
    },
    "buildType": {
      "type": "string",
      "enum": [
        "adc",
        "ad",
        "bruiser",
        "mage",
        "support",
        "tank"
      ]
    },
    "buildCategory": {
      "type": "string",
      "enum": [
        "meta",
        "off-meta",
        "fun"
      ]
    },
    "info": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "notes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "how it works": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "how to play": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "summonerSpells": {
      "type": "array",
      "items": {
        "enum": [
          "barrier",
          "clarity",
          "cleanse",
          "exhaust",
          "flash",
          "ghost",
          "mark",
          "heal",
          "ignite"
        ]
      },
      "uniqueItems": true
    },
    "quickSkillOrder": {
      "type": "string"
    },
    "runes": {
      "type": "object",
      "properties": {
        "major": {
          "type": "object",
          "properties": {
            "configuration": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "press",
                  "lethal",
                  "fleet",
                  "conqueror",
                  "overheal",
                  "triumph",
                  "presence",
                  "alacrity",
                  "tenacity",
                  "bloodline",
                  "coup",
                  "cut",
                  "last",
                  "electrocute",
                  "predator",
                  "dark",
                  "hail",
                  "cheap",
                  "taste",
                  "sudden",
                  "zombie",
                  "ghost",
                  "eyeball",
                  "treasure",
                  "ingenious",
                  "relentless",
                  "ultimate",
                  "summon",
                  "arcane",
                  "phase",
                  "nullifying",
                  "manaflow",
                  "nimbus",
                  "transcendence",
                  "celerity",
                  "absolute",
                  "scorch",
                  "waterwalking",
                  "gathering",
                  "grasp",
                  "aftershock",
                  "guardian",
                  "demolish",
                  "font",
                  "shield",
                  "conditioning",
                  "second",
                  "bone",
                  "overgrowth",
                  "revitalize",
                  "unflinching",
                  "glacial",
                  "unsealed",
                  "first",
                  "hextech",
                  "magical",
                  "perfect",
                  "futures",
                  "minion",
                  "biscuit",
                  "cosmic",
                  "approach",
                  "time"
                ]
              }
            },
            "tree": {
              "type": "string",
              "enum": [
                "Precision",
                "Domination",
                "Sorcery",
                "Resolve",
                "Inspiration"
              ]
            }
          }
        },
        "minor": {
          "type": "object",
          "properties": {
            "configuration": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "press",
                  "lethal",
                  "fleet",
                  "conqueror",
                  "overheal",
                  "triumph",
                  "presence",
                  "alacrity",
                  "tenacity",
                  "bloodline",
                  "coup",
                  "cut",
                  "last",
                  "electrocute",
                  "predator",
                  "dark",
                  "hail",
                  "cheap",
                  "taste",
                  "sudden",
                  "zombie",
                  "ghost",
                  "eyeball",
                  "treasure",
                  "ingenious",
                  "relentless",
                  "ultimate",
                  "summon",
                  "arcane",
                  "phase",
                  "nullifying",
                  "manaflow",
                  "nimbus",
                  "transcendence",
                  "celerity",
                  "absolute",
                  "scorch",
                  "waterwalking",
                  "gathering",
                  "grasp",
                  "aftershock",
                  "guardian",
                  "demolish",
                  "font",
                  "shield",
                  "conditioning",
                  "second",
                  "bone",
                  "overgrowth",
                  "revitalize",
                  "unflinching",
                  "glacial",
                  "unsealed",
                  "first",
                  "hextech",
                  "magical",
                  "perfect",
                  "futures",
                  "minion",
                  "biscuit",
                  "cosmic",
                  "approach",
                  "time"
                ]
              }
            },
            "tree": {
              "type": "string",
              "enum": [
                "Precision",
                "Domination",
                "Sorcery",
                "Resolve",
                "Inspiration"
              ]
            }
          }
        },
        "passive": {
          "type": "object",
          "properties": {
            "configuration": {
              "type": "array",
              "items": [
                {
                  "enum": [
                    "adaptive",
                    "as",
                    "haste"
                  ]
                },
                {
                  "enum": [
                    "adaptive",
                    "armor",
                    "mr"
                  ]
                },
                {
                  "enum": [
                    "hp",
                    "armor",
                    "mr"
                  ]
                }
              ],
              "minItems": 3,
              "maxItems": 3
            },
            "tree": {
              "type": "string",
              "enum": [
                "Passive"
              ]
            }
          }
        }
      }
    },
    "itemSets": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string"
          },
          "items": {
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "Abyssal Mask",
                "Aegis of the Legion",
                "Aether Wisp",
                "Amplifying Tome",
                "Anathema's Chains",
                "Anti-tower Socks",
                "Archangel's Staff",
                "Ardent Censer",
                "Axiom Arc",
                "Bami's Cinder",
                "Bandleglass Mirror",
                "Banshee's Veil",
                "Berserker's Greaves",
                "B. F. Sword",
                "Black Cleaver",
                "Black Mist Scythe",
                "Blade of The Ruined King",
                "Blasting Wand",
                "Blighting Jewel",
                "Bloodthirster",
                "Bloodward",
                "Boots",
                "Boots of Swiftness",
                "Bramble Vest",
                "Broken Stopwatch",
                "Bulwark of the Mountain",
                "Caesura",
                "Catalyst of Aeons",
                "Caulfield's Warhammer",
                "Ceaseless Hunger",
                "Chain Vest",
                "Chempunk Chainsword",
                "Chemtech Putrifier",
                "Cloak of Agility",
                "Cloth Armor",
                "Commencing Stopwatch",
                "Control Ward",
                "Corrupting Potion",
                "Cosmic Drive",
                "Crown of the Shattered Queen",
                "Crystalline Bracer",
                "Cull",
                "Dagger",
                "Dark Seal",
                "Dead Man's Plate",
                "Death's Dance",
                "Death's Daughter500 Silver Serpents",
                "Deicide",
                "Demonic Embrace",
                "Divine Sunderer",
                "Doran's Blade",
                "Doran's Ring",
                "Doran's Shield",
                "Draktharr's Shadowcarver",
                "Dreamshatter",
                "Duskblade of Draktharr",
                "Eclipse",
                "Edge of Night",
                "Elixir of Iron",
                "Elixir of Sorcery",
                "Elixir of Wrath",
                "Emberknife",
                "Equinox",
                "Essence Reaver",
                "Eternal Winter",
                "Evenshroud",
                "Everfrost",
                "Executioner's Calling",
                "Eye of Luden",
                "Eye of the Herald",
                "Faerie Charm",
                "Farsight Alteration",
                "Fiendish Codex",
                "Fimbulwinter",
                "Fire at Will500 Silver Serpents",
                "Forbidden Idol",
                "Force of Nature",
                "Fortification",
                "Frostfang",
                "Frozen Fist",
                "Frozen Heart",
                "Galeforce",
                "Gangplank Placeholder",
                "Gargoyle Stoneplate",
                "Giant's Belt",
                "Glacial Buckler",
                "Goredrinker",
                "Guardian Angel",
                "Guardian's Blade",
                "Guardian's Hammer",
                "Guardian's Horn",
                "Guardian's Orb",
                "Guinsoo's Rageblade",
                "Gusto",
                "Gustwalker Hatchling",
                "Hailblade",
                "Harrowing Crescent",
                "Health Potion",
                "Hearthbound Axe",
                "Heartsteel",
                "Hexdrinker",
                "Hextech Alternator",
                "Hextech Rocketbelt",
                "Horizon Focus",
                "Hullbreaker",
                "Icathia's Curse",
                "Iceborn Gauntlet",
                "Immortal Shieldbow",
                "Imperial Mandate",
                "Infinite Convergence",
                "Infinity Edge",
                "Infinity Force",
                "Echoes of Helia",
                "Ionian Boots of Lucidity",
                "Ironspike Whip",
                "Jak'Sho, The Protean",
                "Kalista's Black Spear",
                "Kindlegem",
                "Kircheis Shard",
                "Knight's Vow",
                "Kraken Slayer",
                "Last Whisper",
                "Leeching Leer",
                "Leviathan",
                "Liandry's Anguish",
                "Liandry's Lament",
                "Lich Bane",
                "Lightning Rod",
                "Locket of the Iron Solari",
                "Long Sword",
                "Lord Dominik's Regards",
                "Lost Chapter",
                "Luden's Tempest",
                "Manamune",
                "Maw of Malmortius",
                "Mejai's Soulstealer",
                "Mercurial Scimitar",
                "Mercury's Treads",
                "Mikael's Blessing",
                "Minion Dematerializer",
                "Mobility Boots",
                "Moonstone Renewer",
                "Morellonomicon",
                "Mortal Reminder",
                "Mosstomper Seedling",
                "Muramana",
                "Nashor's Tooth",
                "Navori Quickblades",
                "Needlessly Large Rod",
                "Negatron Cloak",
                "Night Harvester",
                "Noonquiver",
                "Null-Magic Mantle",
                "Oblivion Orb",
                "Obsidian Edge",
                "Oracle Lens",
                "Overcharged",
                "OvererchargedHA",
                "Pauldrons of Whiterock",
                "Penetrating Bullets",
                "Perfectly Timed Stopwatch",
                "Phage",
                "Phantom Dancer",
                "Phreakish Gusto",
                "Pickaxe",
                "Plated Steelcaps",
                "Poro-Snax",
                "Primordial Dawn",
                "Prowler's Claw",
                "Quicksilver Sash",
                "Rabadon's Deathcap",
                "Radiant Virtue",
                "Rageknife",
                "Raise Morale500 Silver Serpents",
                "Randuin's Omen",
                "Rapid Firecannon",
                "Ravenous Hydra",
                "Recurve Bow",
                "Redemption",
                "Refillable Potion",
                "Reinforced Armor",
                "Rejuvenation Bead",
                "Relic Shield",
                "Reliquary of the Golden Dawn",
                "Riftmaker",
                "Rod of Ages",
                "Ruby Crystal",
                "Runaan's Hurricane",
                "Runesteel Spaulders",
                "Rylai's Crystal Scepter",
                "Sandshrike's Claw",
                "Sapphire Crystal",
                "Scarecrow Effigy",
                "Scorchclaw Pup",
                "Seat of Command",
                "Seeker's Armguard",
                "Seraph's Embrace",
                "Serpent's Fang",
                "Serrated Dirk",
                "Serylda's Grudge",
                "Shadowflame",
                "Shard of True Ice",
                "Sheen",
                "Shurelya's Battlesong",
                "Shurelya's Requiem",
                "Silvermere Dawn",
                "Slightly Magical Footwear",
                "Sorcerer's Shoes",
                "Spear of Shojin",
                "Spectral Sickle",
                "Spectre's Cowl",
                "Spellthief's Edge",
                "Spirit Visage",
                "Staff of Flowing Water",
                "Starcaster",
                "Stealth Ward",
                "Steel Shoulderguards",
                "Sterak's Gage",
                "Stirring Wardstone",
                "Stopwatch",
                "Stormrazor",
                "Stridebreaker",
                "Statikk Shiv",
                "Structure Bounty",
                "Sunfire Aegis",
                "Super Mech Armor",
                "Super Mech Power Field",
                "Syzygy",
                "Targon's Buckler",
                "Tear of the Goddess",
                "The Collector",
                "The Golden Spatula",
                "The Unspoken Parasite",
                "Thornmail",
                "Tiamat",
                "Titanic Hydra",
                "Total Biscuit of Everlasting Will",
                "Tower Power-Up",
                "Trinity Force",
                "Turbo Chemtank",
                "Turret Plating",
                "Typhoon",
                "Umbral Glaive",
                "Upgraded Aeropack",
                "Vampiric Scepter",
                "Vanguard",
                "Verdant Barrier",
                "Vespertide",
                "Vigilant Wardstone",
                "Void Staff",
                "Warden's Eye",
                "Warden's Mail",
                "Warmog's Armor",
                "Watchful Wardstone",
                "Winged Moonplate",
                "Winter's Approach",
                "Wit's End",
                "Wyrmfallen Sacrifice",
                "Youmuu's Ghostblade",
                "Your Cut",
                "Zeal",
                "Zeke's Convergence",
                "Zhonya's Hourglass"
              ]
            }
          }
        }
      }
    }
  },
  "required": [
    "champion",
    "sanitizedName",
    "name",
    "buildType",
    "buildCategory",
    "info",
    "summonerSpells",
    "quickSkillOrder",
    "runes",
    "itemSets"
  ]
}

=== wrekah/community-builds/builds/shaco/support-healer-radiant.json
{
  "champion": "Shaco",
  "sanitizedName": "shaco",
  "name": "Healer Tank",
  "buildType": "tank",
  "buildCategory": "fun",
  "info": {
    "description": "Need some heal? Feeling to play something interesting today? One Knockoff Soraka for you.",
    "how to play": [
      "This build works best, when your team drafted full damage (AGAIN) and you need both frontline and sustain in fights (note: use a normal tank/dmg build, when you have insane bruiser-healing such as Mundo/Olaf/Fiora/Soraka/Vlad).",
      "You won't be most tanky with this build, however you have tools to survive long enough to soak damage and disrupt fights.",
      "Engage with snowball, stay around enemies for a bit to disrupt and soak damage, use ult (Radiant Virtue procs on clone as well). Use Q to get out if you are low. Otherwise use Q to reposition and annoy enemy backline. Heal up with Warmog's Armor if you ever get low. Rinse and repeat.",
      "Rush first Radiant Virtue, second Redemption.",
      "Use Redemption as often as possible to (mostly) heal your allies.",
      "Your E heals! It triggers Font of Life for your allies. Both passive and active part. So, it sometimes makes sense to not E at all, and just auto attack for more healing.",
      "Your W and your R also heals!",
      "Adapt to enemy team. They heavy AP? Buy MR. They heavy AD? Buy Armor."
    ],
    "credit": "miruk @EUW"
  },
  "summonerSpells": [
    "mark",
    "flash"
  ],
  "quickSkillOrder": "wqe",
  "runes": {
    "major": {
      "configuration": [
        "guardian",
        "font",
        "second",
        "overgrowth"
      ],
      "tree": "Resolve"
    },
    "minor": {
      "configuration": [
        "eyeball",
        "ingenious"
      ],
      "tree": "Domination"
    },
    "passive": {
      "configuration": [
        "haste",
        "mr",
        "hp"
      ],
      "tree": "Passive"
    }
  },
  "itemSets": [
    {
      "description": "Starting items",
      "items": [
        "Ruby Crystal",
        "Null-Magic Mantle",
        "Tear of the Goddess"
      ]
    },
    {
      "description": "Rush this",
      "items": [
        "Radiant Virtue",
        "Redemption"
      ]
    },
    {
      "description": "Boots",
      "items": [
        "Ionian Boots of Lucidity",
        "Mercury's Treads",
        "Plated Steelcaps"
      ]
    },
    {
      "description": "Damage items",
      "items": [
        "Imperial Mandate",
        "Demonic Embrace",
        "Rabadon's Deathcap",
        "Void Staff"
      ]
    },
    {
      "description": "Good support items",
      "items": [
        "Chemtech Putrifier",
        "Staff of Flowing Water",
        "Ardent Censer"
      ]
    },
    {
      "description": "Situational items",
      "tooltip": [
        "<div><b>Ardent Censer</b> - your team has auto attackers. </br></br><b>Zeke's Convergence</b> - your team has auto attackers + coordination required.</br></br><b>Mikael's Blessing</b> - coordination required.</br></br><b>Knight's Vow</b> - situational, it's okay if you can stay close.</br></br>These items provide <b>shield and heal power</b> buff, which sometimes make it OK to buy just for that.</div>"
      ],
      "items": [
        "Ardent Censer",
        "Zeke's Convergence",
        "Mikael's Blessing",
        "Knight's Vow"
      ]
    },
    {
      "description": "For mana problems",
      "items": [
        "Tear of the Goddess",
        "Seraph's Embrace"
      ]
    },
    {
      "description": "Good MR items",
      "items": [
        "Abyssal Mask",
        "Spirit Visage",
        "Force of Nature",
        "Turbo Chemtank"
      ]
    },
    {
      "description": "Good Armor items",
      "items": [
        "Frozen Heart",
        "Thornmail",
        "Sunfire Aegis",
        "Randuin's Omen",
        "Dead Man's Plate"
      ]
    },
    {
      "description": "Situational items",
      "items": [
        "Banshee's Veil",
        "Zhonya's Hourglass"
      ]
    },
    {
      "description": "For the last fight",
      "tooltip": [
        "<div><b>Elixir of Iron</b> - for more survivability and heals from Radiant Virtue. </br></br><b>Elixir of Sorcery</b> - more damage.</br></br></div>"
      ],
      "items": [
        "Elixir of Iron",
        "Elixir of Sorcery",
        "Stopwatch"
      ]
    },
    {
      "description": "Example final build",
      "items": [
        "Ionian Boots of Lucidity",
        "Radiant Virtue",
        "Redemption",
        "Staff of Flowing Water",
        "Warmog's Armor",
        "Abyssal Mask"
      ]
    }
  ]
}

=== wrekah/community-builds/builds/vi/tank-shield-mana.json
{
  "champion": "Vi",
  "sanitizedName": "vi",
  "name": "Shield Tank",
  "buildType": "tank",
  "buildCategory": "fun",
  "info": {
    "description": "Not enough HP? Just double it with the all shields you are getting!",
    "tags": [
      "Tank",
      "Meta"
    ],
    "how to play": [
      "The idea of the build is centered around shielding.",
      "The shield you get from Passive scales with HP, so Heartsteel, Grasp and Overgrowth runes give it a big buff. Combine this with shields you get from Sterak's and Fimbulwinter plus the shield boost from Spirit Visage and you basically double your HP with the shields you get!",
      "Remember to watch cooldown of your passive! In the early game, wait for it to be up, before going in. Late game, remember that triggering W reduces your Passive cooldown. It means that sometimes you will survive longer by fighting (and triggering Passive more often), rather than running!",
      "Adapt to enemy team. Buy items that counter them. They heavy AP? Stack MR. They heavy AD? Stack Armor. Your team does not have damage? Buy recommended items for bruiser or for pure damage!",
      "Do not be shy and do not wait for 'special moment'. You have great engaging and catching tools - Q and R!",
      "Enemy team heavy on AP? Buy MR. They heavy on AD? Buy Armor. You need some damage? Well buy that.",
      "Remember to consume your Heartsteel procs!",
      "Remember to consume your Grasp of the Undying procs!"
    ],
    "credit": "OverdriverJC @EUNE"
  },
  "summonerSpells": [
    "mark",
    "flash"
  ],
  "quickSkillOrder": "qew",
  "runes": {
    "major": {
      "configuration": [
        "grasp",
        "shield",
        "second",
        "overgrowth"
      ],
      "tree": "Resolve"
    },
    "minor": {
      "configuration": [
        "ingenious",
        "cheap"
      ],
      "tree": "Domination"
    },
    "passive": {
      "configuration": [
        "as",
        "armor",
        "mr"
      ],
      "tree": "Passive"
    }
  },
  "itemSets": [
    {
      "description": "Starting items",
      "items": [
        "Guardian's Horn",
        "Tear of the Goddess"
      ]
    },
    {
      "description": "Boots",
      "items": [
        "Mercury's Treads",
        "Plated Steelcaps",
        "Ionian Boots of Lucidity"
      ]
    },
    {
      "description": "Rush this",
      "items": [
        "Heartsteel"
      ]
    },
    {
      "description": "Good tanky items",
      "items": [
        "Warmog's Armor",
        "Fimbulwinter",
        "Gargoyle Stoneplate"
      ]
    },
    {
      "description": "Good MR items",
      "items": [
        "Spirit Visage",
        "Abyssal Mask",
        "Force of Nature",
        "Turbo Chemtank"
      ]
    },
    {
      "description": "Good Armor items",
      "items": [
        "Sunfire Aegis",
        "Thornmail",
        "Frozen Heart",
        "Randuin's Omen",
        "Dead Man's Plate"
      ]
    },
    {
      "description": "Situational - going bruiser",
      "items": [
        "Titanic Hydra",
        "Death's Dance"
      ]
    },
    {
      "description": "Situational - for more dmg",
      "items": [
        "Ravenous Hydra",
        "Blade of The Ruined King"
      ]
    },
    {
      "description": "Example final build",
      "items": [
        "Mercury's Treads",
        "Heartsteel",
        "Fimbulwinter",
        "Sterak's Gage",
        "Spirit Visage",
        "Sunfire Aegis"
      ]
    }
  ]
}
